# Generated by Django 4.2.13 on 2024-06-06 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('year', models.IntegerField()),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Janr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_pay', models.BooleanField()),
                ('price', models.IntegerField()),
                ('update_time', models.DateTimeField()),
                ('id_game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gamewarrior.game')),
                ('id_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gamewarrior.janr')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.TextField()),
                ('nickname', models.TextField()),
                ('password', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('datareg', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gamewarrior.game')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gamewarrior.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gamewarrior.user'),
        ),
        migrations.AddField(
            model_name='game',
            name='janr_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gamewarrior.janr'),
        ),
    ]
