# Generated by Django 4.2.13 on 2024-06-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamewarrior', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='developer',
            field=models.TextField(default='default title'),
        ),
        migrations.AddField(
            model_name='game',
            name='publisher',
            field=models.TextField(default='default title'),
        ),
    ]
