# Generated by Django 4.2.13 on 2024-06-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamewarrior', '0002_game_developer_game_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to='img/'),
        ),
    ]
