# Generated by Django 4.2.13 on 2024-06-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamewarrior', '0003_game_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='image',
            new_name='imagecar1',
        ),
        migrations.AddField(
            model_name='game',
            name='imagecar2',
            field=models.ImageField(max_length=255, null=True, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='game',
            name='imagecar3',
            field=models.ImageField(max_length=255, null=True, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='game',
            name='imagecar4',
            field=models.ImageField(max_length=255, null=True, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='game',
            name='imagecar5',
            field=models.ImageField(max_length=255, null=True, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='game',
            name='imagemain',
            field=models.ImageField(max_length=255, null=True, upload_to='img/'),
        ),
    ]
