# Generated by Django 4.2.13 on 2024-06-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamewarrior', '0006_alter_order_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='imagecar1',
            field=models.TextField(default='default title'),
        ),
        migrations.AlterField(
            model_name='game',
            name='imagecar2',
            field=models.TextField(default='default title'),
        ),
        migrations.AlterField(
            model_name='game',
            name='imagecar3',
            field=models.TextField(default='default title'),
        ),
        migrations.AlterField(
            model_name='game',
            name='imagecar4',
            field=models.TextField(default='default title'),
        ),
        migrations.AlterField(
            model_name='game',
            name='imagecar5',
            field=models.TextField(default='default title'),
        ),
        migrations.AlterField(
            model_name='game',
            name='imagemain',
            field=models.TextField(default='default title'),
        ),
    ]
