# Generated by Django 5.0.6 on 2024-06-22 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamewarrior', '0009_tag_tagsofgame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlist',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='orderlist',
            name='game_id',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderList',
        ),
    ]
